spring:
  profiles:
    active: dev  # Ce profil est activé par défaut

---

spring:
  config:
    activate:
      on-profile: dev

greeting:
  message: Bonjour NEO

---
# commande à utiliser en terminal pour avoir le message en prod
# mvn spring-boot:run "-Dspring-boot.run.profiles=prod"

spring:
  config:
    activate:
      on-profile: prod

greeting:
  message: Bonjour ORACLE
